name: Test Lambda Get-Date-Function

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
  
    steps:
      - name: invoke-aws-lambda
        uses: gagoar/invoke-aws-lambda@v3.3.2
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REGION: us-west-1
          FunctionName: Get-Date-Function
          Payload: '{}'